services:
  db:
    image: postgres:latest
    container_name: bibliothDB
    environment:
      POSTGRES_USER: bUser
      POSTGRES_PASSWORD: bPassword
      POSTGRES_DB: Biblioth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
